services:
  frauder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frauder
    restart: unless-stopped
    environment:
      KAFKA_BROKERS: fraud-kafka:29092
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TRANSACTIONS_TOPIC: transactions
    networks:
      - fraud-network
      - shared-network
    depends_on:
      - redis
      - kafka
      - zookeeper
    command: >
      sh -c "
        echo 'Waiting for Kafka to be ready...' &&
        while ! nc -zv fraud-kafka 29092 2>/dev/null; do
          echo 'Waiting for Kafka...' &&
          sleep 3
        done &&
        echo 'Kafka is ready!' &&
        python -m app.main"

  redis:
    image: redis:alpine
    container_name: fraud-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - fraud-network
      - shared-network
      
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: python-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fraud-network
      - shared-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: python-kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Auto-create topics with default settings
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - fraud-network
      - shared-network
      
  # Add a service to create the transactions topic
  kafka-setup:
    image: confluentinc/cp-kafka:latest
    container_name: python-kafka-setup
    depends_on:
      - kafka
    command: >
      bash -c '
        echo "Waiting for Kafka to be ready..." &&
        cub kafka-ready -b kafka:29092 1 30 &&
        echo "Creating topics..." &&
        kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 --topic transactions &&
        echo "Topics created."
      '
    networks:
      - fraud-network

networks:
  fraud-network:
    name: python-fraud-network
  shared-network:
    name: shared-fraud-network